import { db } from '../config/firebase-config.js';
import { authManager } from '../auth/auth.js';

class ReportGenerator {
    constructor() {
        this.setupEventListeners();
    }

    initialize() {
        this.generatePreview();
    }

    setupEventListeners() {
        document.getElementById('generate-report-btn')?.addEventListener('click', () => this.generatePDFReport());
    }

    async generatePreview() {
        const previewDiv = document.getElementById('report-preview-content');
        if (!previewDiv) return;
        
        try {
            const devices = await this.getDevices();
            const metrics = await this.getMetrics();
            const topology = await this.getTopologySnapshot();
            
            previewDiv.innerHTML = `
                <div class="report-preview">
                    <div class="preview-header">
                        <h3>NetworkPulse Report</h3>
                        <p>Generated: ${new Date().toLocaleString()}</p>
                        <p>Generated by: ${authManager.currentUser?.displayName || authManager.currentUser?.email}</p>
                    </div>
                    
                    <div class="preview-section">
                        <h4>Network Overview</h4>
                        <div class="stats-grid">
                            <div class="stat">
                                <span class="stat-label">Total Devices:</span>
                                <span class="stat-value">${devices.length}</span>
                            </div>
                            <div class="stat">
                                <span class="stat-label">Active Devices:</span>
                                <span class="stat-value">${devices.filter(d => d.status === 'active').length}</span>
                            </div>
                            <div class="stat">
                                <span class="stat-label">Network Health:</span>
                                <span class="stat-value">${metrics.healthScore || 98}%</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="preview-section">
                        <h4>Device Inventory</h4>
                        <table class="preview-table">
                            <thead>
                                <tr>
                                    <th>Device Name</th>
                                    <th>Type</th>
                                    <th>IP Address</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${devices.slice(0, 5).map(device => `
                                    <tr>
                                        <td>${device.name}</td>
                                        <td>${device.type}</td>
                                        <td>${device.ip}</td>
                                        <td>${device.status}</td>
                                    </tr>
                                `).join('')}
                            </tbody>
                        </table>
                        ${devices.length > 5 ? `<p class="note">... and ${devices.length - 5} more devices</p>` : ''}
                    </div>
                    
                    <div class="preview-section">
                        <h4>Performance Metrics</h4>
                        <div class="metrics-summary">
                            <p>Average Bandwidth: ${this.calculateAverage(metrics.bandwidth)} Mbps</p>
                            <p>Average Latency: ${this.calculateAverage(metrics.latency)} ms</p>
                            <p>Average Packet Loss: ${this.calculateAverage(metrics.packetLoss)}%</p>
                        </div>
                    </div>
                    
                    <div class="preview-section">
                        <h4>Topology Summary</h4>
                        <p>Nodes: ${topology.nodes}</p>
                        <p>Connections: ${topology.links}</p>
                        <p>Network Type: ${topology.type}</p>
                    </div>
                </div>
            `;
        } catch (error) {
            console.error('Error generating preview:', error);
            previewDiv.innerHTML = '<p>Error loading report preview. Please try again.</p>';
        }
    }

    async generatePDFReport() {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF('p', 'mm', 'a4');
        
        try {
            const devices = await this.getDevices();
            const metrics = await this.getMetrics();
            const topology = await this.getTopologySnapshot();
            
            // Title
            doc.setFontSize(24);
            doc.setTextColor(0, 212, 255);
            doc.text('NetworkPulse Report', 20, 20);
            
            // Metadata
            doc.setFontSize(10);
            doc.setTextColor(100, 100, 100);
            doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30);
            doc.text(`Generated by: ${authManager.currentUser?.displayName || authManager.currentUser?.email}`, 20, 35);
            
            // Network Overview
            doc.setFontSize(16);
            doc.setTextColor(0, 0, 0);
            doc.text('Network Overview', 20, 50);
            
            doc.setFontSize(12);
            doc.text(`Total Devices: ${devices.length}`, 20, 60);
            doc.text(`Active Devices: ${devices.filter(d => d.status === 'active').length}`, 20, 65);
            doc.text(`Network Health: ${metrics.healthScore || 98}%`, 20, 70);
            
            // Device Inventory
            doc.setFontSize(16);
            doc.text('Device Inventory', 20, 85);
            
            let yPos = 95;
            doc.setFontSize(10);
            devices.slice(0, 15).forEach(device => {
                if (yPos > 270) {
                    doc.addPage();
                    yPos = 20;
                }
                doc.text(`${device.name} (${device.type}) - ${device.ip} - ${device.status}`, 20, yPos);
                yPos += 5;
            });
            
            if (devices.length > 15) {
                doc.text(`... and ${devices.length - 15} more devices`, 20, yPos);
                yPos += 5;
            }
            
            // Performance Metrics
            if (yPos > 250) {
                doc.addPage();
                yPos = 20;
            }
            
            doc.setFontSize(16);
            doc.text('Performance Metrics', 20, yPos + 10);
            
            doc.setFontSize(12);
            doc.text(`Average Bandwidth: ${this.calculateAverage(metrics.bandwidth)} Mbps`, 20, yPos + 20);
            doc.text(`Average Latency: ${this.calculateAverage(metrics.latency)} ms`, 20, yPos + 25);
            doc.text(`Average Packet Loss: ${this.calculateAverage(metrics.packetLoss)}%`, 20, yPos + 30);
            
            // Save the PDF
            doc.save(`network-report-${Date.now()}.pdf`);
            
            authManager.showToast('Report generated successfully!', 'success');
            
        } catch (error) {
            console.error('Error generating PDF:', error);
            authManager.showToast('Failed to generate report', 'error');
        }
    }

    async getDevices() {
        const snapshot = await db.collection('devices').get();
        const devices = [];
        snapshot.forEach(doc => {
            devices.push({ id: doc.id, ...doc.data() });
        });
        return devices;
    }

    async getMetrics() {
        const snapshot = await db.collection('metrics').orderBy('timestamp', 'desc').limit(100).get();
        const metrics = {
            bandwidth: [],
            latency: [],
            packetLoss: [],
            healthScore: 98
        };
        
        snapshot.forEach(doc => {
            const data = doc.data();
            if (data.bandwidth) metrics.bandwidth.push(data.bandwidth);
            if (data.latency) metrics.latency.push(data.latency);
            if (data.packetLoss) metrics.packetLoss.push(data.packetLoss);
        });
        
        return metrics;
    }

    async getTopologySnapshot() {
        const devicesSnapshot = await db.collection('devices').get();
        const connectionsSnapshot = await db.collection('connections').get();
        
        return {
            nodes: devicesSnapshot.size,
            links: connectionsSnapshot.size,
            type: 'Hybrid'
        };
    }

    calculateAverage(array) {
        if (!array || array.length === 0) return 0;
        const sum = array.reduce((a, b) => a + b, 0);
        return (sum / array.length).toFixed(1);
    }
}

export const reportGenerator = new ReportGenerator();